### ISSUE TITLE
Escape key is not recognized as correct Enum and not returned immediately

### ISSUE THREAD

**Issue by MichaelAquilina** [mitsuhiko/console#66] opened 2020-05-20 20:48 UTC
There are two (possibly related issues here)

When I press the escape key when running `term.read_key()`, nothing is returned until another (anything will do) key is pressed. 

Regardless of what the second key pressed is, the value returned is not `Key::Escape` but `Key::Char('\u{2b}')`

I was digging into the source code and noticed this message that could point to where the issue might lie?

https://github.com/mitsuhiko/console/blob/9aab753cc811b3fed824c85c0e17b34042dd5ab9/src/unix_term.rs#L92

**Comment by pksunkara** [comment] 2020-05-20 20:56
Yeah, @rjwalters recently improved the function in #62, but to my embarrasment I forgot about the scenario where the user just wants to press ESC and nothing else.

**Comment by MichaelAquilina** [comment] 2020-05-20 21:14
I've confirmed this is only an issue in 0.11.3. I've pinned console to 0.11.2 in the meanwhile which fixes the issue

**Comment by atanunq** [comment] 2020-10-05 23:50
I stumbled upon this issue when looking for a way to read a a sequence of bytes from stdin. The first one of them is `Key::Escape` and thus I lose most of the subsequent ones. I cannot solve the issue by pinning to `0.11.2` because it `libc::read`s in chunks of 20 bytes and `key_from_escape_codes` returns only the first char. Am I correct to think that this should be fixed? If so, can I help with something?

**Comment by pksunkara** [comment] 2020-10-06 06:26
I am always open for PRs. Unfortunately I currently can't fix this.

**Comment by atanunq** [comment] 2020-10-08 22:48
I had a go with it but I cannot come up with a solution that will cover all cases. Would love to get some feedback, though, as I have never used FFI in Rust. Or written any C, for that matter.

In general, my thinking is as follows:
To fix the blocking on escape issue, I use [poll](https://docs.rs/libc/0.2.79/libc/fn.poll.html) to check whether there is something to be read from the fd after Esc has been pressed. If not, return the key immediately. If yes, continue reading bytes one by one until we find something familiar. Again with poll, `read_single_key` will block if there is nothing to be read at all.

To achieve this I created a `read_single_byte` function that will immediately read, or return None if the fd is not ready.

The problem is if we have read, for example, Esc and one more character and the sequence is not recognized. Then this char is lost if only Esc is returned. I was thinking of adding an additional Key enum, `UnknownEscSeq`, that can hold the consumed char. However, I cannot figure out how to hold more than 1 chars there in an efficient manner.

The branch is [here](https://github.com/atanunq/console/tree/read-escape-key). It is still in progress, as support for many more keys could be added ([rustyline](https://github.com/kkawakam/rustyline) is a good reference). I might have gone off track, but do you think the approach makes sense?

**Comment by pksunkara** [comment] 2020-10-09 09:14
Note: There is a related issue at https://github.com/mitsuhiko/dialoguer/issues/82

I think the approach you have is probably the best, but I haven't researched how other famous libraries in other languages achieve this. We can try to take some inspiration from them.

**Closed** 2020-10-11 14:27 UTC
